### PR TITLE
Add test workflow

### LINKED ISSUE #6: Add test GitHub Actions workflow
This would be beneficial to have tests that auto-run on each PR! 😎

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would...
- [x] Add a GitHub workflow to run `npm test` on each push to main and each PR that's opened against main

closes #6

### CODE REVIEW

**Comment by jimmywarting** [comment]
Cool! thanks for this. 

At the moment this have really only been working on nodejs v19 atm cuz i was using `--import` flag to pre run some code before the user code executes 
(to set up all the globalThis properties and making it a instance of EventTarget, adding globalThis.onmessage, among other things)

but `--import` did only work on v19 +
i didn't really feel like converting it to cjs...
so i found a solution in #4 that instead makes it so the actual code that you want to load becomes something else.

so when you do
```js
new Worker('./foo.js')
```
then you will instead actually create a worker that looks something like:
```js
import 'whatwg-worker/pre-run.js'
import './foo.js'
```

Anyhow i would really like to test out different NodeJS versions
particularly on v16 and v18

v20 isn't currently working as it should as `--experimental-loader` to make http, and blob imports stop working when using worker_threads
so still need to work out some quirks there. related issue is: https://github.com/nodejs/node/issues/47747

---

Anyhow can you change this so it test v16 and v18?

**Comment by jcbhmr** [comment]
Done! Added matrix to test on v16 v18 and v20

**Comment by jcbhmr** [comment]
> so when you do
> 
> ```js
> new Worker('./foo.js')
> ```
> 
> then you will instead actually create a worker that looks something like:
> 
> ```js
> import 'whatwg-worker/pre-run.js'
> import './foo.js'
> ```

This is the gist of what I assumed was happening 😆

**Comment by jimmywarting** [comment]
Earlier i did kind of `node --import ./pre-run.js ./foo.js` but that wasn't so good for <19

**Review by jimmywarting — APPROVED** [review]

**Pull request merged**
